# Generated by Django 3.0.5 on 2023-10-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231028_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='category',
        ),
    ]
